
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: social_cap_development
  username: postgres
  password: postgres


# test:
#   <<: *default
#   database: social_network_test
#   username: postgres
#   password: postgres


# production:
#   <<: *default
#   database: social_network_production
#   username: postgres
#   password: postgres
